### PR TITLE
W22 Release

### PR DESCRIPTION
**Pull request by achitta**

### CODE REVIEW

**Review by awdeorio — APPROVED** [review]
LGTM, but versions don't match `main` in the P3 repo.  I assume you're going to post a PR that matches?

**Comment by achitta** [comment]
image
@awdeorio any ideas on how to fix this? Don't have too much experience with Docker so not really sure how to grant root access

**Comment by achitta** [comment]
```
# Build project 3 image
FROM eecs485/ag_base:latest

# Install NodeJS LTS
RUN apt-get install -y curl
RUN curl -sL https://deb.nodesource.com/setup_lts.x | bash - && apt-get install -y nodejs
RUN apt-get remove -y curl

# Install Google Chrome
ADD https://dl-ssl.google.com/linux/linux_signing_key.pub .
RUN apt-key add linux_signing_key.pub
RUN sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list'
RUN apt-get update && apt-get install -y google-chrome-stable

USER autograder:autograder

# Configure Python virtual environment and install Python packages
COPY requirements.txt .
RUN $PYTHON -m venv env-p3
RUN env-p3/bin/pip install -r requirements.txt

# Install NodeJS packages
COPY package.json .
COPY package-lock.json .

USER root:root

RUN npm install .

USER autograder:autograder

# Install chromedriver (same major version as Google Chrome)
# Since internet access is disabled on the autograder, we need to copy
# the downloaded chromedriver executable to our environment's PATH.
RUN npm install chromedriver --detect_chromedriver_version --no-save; cp node_modules/chromedriver/lib/chromedriver/chromedriver env-p3/bin/chromedriver

RUN rm linux_signing_key.pub requirements.txt

USER root:root
```
Assuming that this is a permissions error, could this work?

**Comment by awdeorio** [comment]
I don't like the "switch to root" idea.  To debug, fire up an interactive session and fiddle around at the CLI.  https://github.com/eecs485staff/p1-insta485-static/blob/main/README_docker.md

**Comment by achitta** [comment]
> I don't like the "switch to root" idea. To debug, fire up an interactive session and fiddle around at the CLI. https://github.com/eecs485staff/p1-insta485-static/blob/main/README_docker.md

Tried building the p3 image from this `ag-docker-images` repo locally and saw this:
```
#19 52.52 npm ERR! code EACCES
#19 52.52 npm ERR! syscall open
#19 52.52 npm ERR! path /home/autograder/working_dir/package-lock.json
#19 52.52 npm ERR! errno -13
#19 52.53 npm ERR! Error: EACCES: permission denied, open '/home/autograder/working_dir/package-lock.json'
#19 52.53 npm ERR!  [Error: EACCES: permission denied, open '/home/autograder/working_dir/package-lock.json'] {
#19 52.53 npm ERR!   errno: -13,
#19 52.53 npm ERR!   code: 'EACCES',
#19 52.53 npm ERR!   syscall: 'open',
#19 52.54 npm ERR!   path: '/home/autograder/working_dir/package-lock.json'
#19 52.54 npm ERR! }
#19 52.54 npm ERR! 
#19 52.54 npm ERR! The operation was rejected by your operating system.
#19 52.54 npm ERR! It is likely you do not have the permissions to access this file as the current user
#19 52.54 npm ERR! 
#19 52.54 npm ERR! If you believe this might be a permissions issue, please double-check the
#19 52.54 npm ERR! permissions of the file and its containing directories, or try running
#19 52.54 npm ERR! the command again as root/Administrator.
#19 52.67 
#19 52.68 npm ERR! A complete log of this run can be found in:
#19 52.68 npm ERR!     /home/autograder/.npm/_logs/2022-02-05T16_41_18_830Z-debug.log
```
And when I checked the file permissions for package.json and package-lock.json, I'm seeing 
```
#19 0.279 -rw-r--r-- 1 root root 987 Feb  4 15:32 package.json
```

So changing to a root user to run `npm install .` works (tested this out), but I haven't found another workaround yet. Tried https://docs.npmjs.com/resolving-eacces-permissions-errors-when-installing-packages-globally this out and it didn't end up working and also tried running using `npm install --unsafe-perm=true` and that didn't work either. Do you have any other ideas?

**Comment by awdeorio** [comment]
Email James Perretta.  He will definitely be able to help.  jameslp@umich.edu

**Comment by awdeorio** [comment]
P.S.  If you are desparate, then just fly as root (like you said) and create an issue to fix it later.

**Pull request merged**
