### PR TITLE
Bump P1 Packages

### PR DESCRIPTION
**Pull request by japplefield**
This PR only updates packages for P1.

I notice that our docker images still use Ubuntu 18.04, which is more than 4 years old now. Should we update to 20.04 or 22.04?

### CODE REVIEW

**Comment by awdeorio** [comment]
> I notice that our docker images still use Ubuntu 18.04, which is more than 4 years old now. Should we update to 20.04 or 22.04?

Yes!

**Review by awdeorio — APPROVED** [review]
LGTM

**Comment by japplefield** [comment]
I updated to 20.04. Updating to 22.04 requires a PR on eecsautograder/base-docker-images which I created: https://github.com/eecs-autograder/base-docker-images/pull/4

**Comment by japplefield** [comment]
Update that I will merge this with 20.04 on Aug 15 if the aforementioned PR is not merged.

**Pull request merged**
